language: php
dist: trusty

sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm-3.21

matrix:
    include:
        - php: "5.3"
          dist: precise
      
before_install:
    - composer self-update

install:
    - composer install

script: vendor/bin/phpunit --config=phpunit.xml.dist
