language: php
dist: trusty

sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - hhvm

matrix:
    allow_failures:
        - php: hhvm
    include:
        - php: "5.3"
          dist: precise

before_install:
    - composer self-update

install:
    - composer install
    # Last released version of htmlpurifier (4.10.0) is broken on HHVM
    # https://github.com/ezyang/htmlpurifier/issues/169
    - if [ "${TRAVIS_PHP_VERSION}" == "hhvm" ]; then composer require 'ezyang/htmlpurifier:dev-master#89b3fe4'; fi
    # PHPUnit 6+ is incompatible with HHVM because of
    # Uncaught Error: array_creation_expression is not allowed in write context
    # in vendor/phpunit/phpunit/src/Framework/TestCase.php:1273
    - if [ "${TRAVIS_PHP_VERSION}" == "hhvm" ]; then composer require 'phpunit/phpunit:5.7.*'; fi

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - if [ -f "vendor/bin/php-coveralls" ]; then php vendor/bin/php-coveralls -v; else vendor/bin/coveralls -v; fi
